const generateRandomAIPost = function() {
    let images = ['/images/1.jpg', '/images/2.jpg', '/images/3.jpg', '/images/4.jpg'];
    let emojis = ["🐕","🐾","🐩","🐶","🐕‍🦺","🦮"].sort( () => .5 - Math.random() );;
    let comments =  ["cool!!!", "This is amazing", "wow this looks great"];
    let userNames = ["bri_123", "sam_got_2", "jennie_smt", "dizzy_candy", "skol34", "hymy_jon"];
    let stories = [
        "This post was generated by AI. How cool is that !!!",
        "Emoji Meaning The cooked sausage of a hot dog in a sliced bun and drizzled with yellow mustard.",
        "The domestic dog is a domesticated descendant of the wolf. ",
        "The dog derived from an ancient, extinct wolf, and the modern grey wolf is the dog's nearest living relative. "
    ];

    return {
      likes: Math.floor(Math.random() * (1000 - 100)) + 100,
      userName: 'devGhostStories',
      story: stories[Math.floor(Math.random()*stories.length)],
      tags: ['ai', 'devghoststories', 'aistories'],
      emojis: emojis.sort( () => 0.5 - Math.random()),
      commentUserName: userNames[Math.floor(Math.random()*userNames.length)],
      comment: comments[Math.floor(Math.random()*comments.length)],
      image: images[Math.floor(Math.random()*images.length)],
    };
}

module.exports = {
    generateRandomAIPost
}